/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  audit_detail: () => import("@/views/audit/detail/[id].vue"),
  audit_list: () => import("@/views/audit/list/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  export_list: () => import("@/views/export/list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  point_list: () => import("@/views/point/list/index.vue"),
  point_management_old: () => import("@/views/point/management_old/index.vue"),
  point_map: () => import("@/views/point/map/index.vue"),
  project_detail: () => import("@/views/project/detail/[id].vue"),
  project_list: () => import("@/views/project/list/index.vue"),
  system_announcement: () => import("@/views/system/announcement/index.vue"),
  system_collab: () => import("@/views/system/collab/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_help: () => import("@/views/system/help/index.vue"),
  system_log: () => import("@/views/system/log/index.vue"),
  system_message: () => import("@/views/system/message/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  task_center_detail: () => import("@/views/task_center/detail/index.vue"),
  task_center_list: () => import("@/views/task_center/list/index.vue"),
  task_center_map: () => import("@/views/task_center/map/index.vue"),
  template_design: () => import("@/views/template/design/[id].vue"),
  template_list: () => import("@/views/template/list/index.vue"),
};
