/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base',
    meta: {
      title: 'audit',
      i18nKey: 'route.audit'
    },
    props: true,
    children: [
      {
        name: 'audit_detail',
        path: '/audit/detail/:id',
        component: 'view.audit_detail',
        meta: {
          title: 'audit_detail',
          i18nKey: 'route.audit_detail'
        }
      },
      {
        name: 'audit_list',
        path: '/audit/list',
        component: 'view.audit_list',
        meta: {
          title: 'audit_list',
          i18nKey: 'route.audit_list'
        }
      }
    ]
  },
  {
    name: 'export',
    path: '/export',
    component: 'layout.base',
    meta: {
      title: 'export',
      i18nKey: 'route.export'
    },
    children: [
      {
        name: 'export_list',
        path: '/export/list',
        component: 'view.export_list',
        meta: {
          title: 'export_list',
          i18nKey: 'route.export_list'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'material-symbols:dashboard-outline-rounded',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'point',
    path: '/point',
    component: 'layout.base',
    meta: {
      title: 'point',
      i18nKey: 'route.point'
    },
    children: [
      {
        name: 'point_list',
        path: '/point/list',
        component: 'view.point_list',
        meta: {
          title: 'point_management',
          i18nKey: 'route.point_management',
          icon: 'material-symbols:assignment-outline-rounded',
          order: 3
        }
      },
      {
        name: 'point_management',
        path: '/point/management',
        component: 'view.point_management',
        meta: {
          title: 'point_management',
          i18nKey: 'route.point_management'
        },
        children: [
          {
            name: 'point_management_old',
            path: '/point/management/old',
            component: 'view.point_management_old',
            meta: {
              title: 'point_management_old',
              i18nKey: 'route.point_management_old'
            }
          }
        ]
      },
      {
        name: 'point_map',
        path: '/point/map',
        component: 'view.point_map',
        meta: {
          title: 'point_map',
          i18nKey: 'route.point_map'
        }
      }
    ]
  },
  {
    name: 'project',
    path: '/project',
    component: 'layout.base',
    meta: {
      title: 'project',
      i18nKey: 'route.project'
    },
    children: [
      {
        name: 'project_detail',
        path: '/project/detail/:id',
        component: 'view.project_detail',
        meta: {
          title: 'project_detail',
          i18nKey: 'route.project_detail'
        }
      },
      {
        name: 'project_list',
        path: '/project/list',
        component: 'view.project_list',
        meta: {
          title: 'project_list',
          i18nKey: 'route.project_list'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    redirect: '/system/user',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'material-symbols:settings-outline-rounded',
      order: 7
    },
    children: [
      {
        name: 'system_help',
        path: '/system/help',
        component: 'view.system_help',
        meta: {
          title: 'system_help',
          i18nKey: 'route.system_help'
        }
      },
      {
        name: 'system_log',
        path: '/system/log',
        component: 'view.system_log',
        meta: {
          title: 'system_log',
          i18nKey: 'route.system_log'
        }
      },
      {
        name: 'system_message',
        path: '/system/message',
        component: 'view.system_message',
        meta: {
          title: 'system_message',
          i18nKey: 'route.system_message'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'material-symbols:group-outline-rounded',
          order: 1
        }
      }
    ]
  },
  {
    name: 'template',
    path: '/template',
    component: 'layout.base',
    meta: {
      title: 'template',
      i18nKey: 'route.template'
    },
    children: [
      {
        name: 'template_design',
        path: '/template/design/:id',
        component: 'view.template_design',
        meta: {
          title: 'template_design',
          i18nKey: 'route.template_design'
        }
      },
      {
        name: 'template_list',
        path: '/template/list',
        component: 'view.template_list',
        meta: {
          title: 'template_list',
          i18nKey: 'route.template_list'
        }
      }
    ]
  }
];
